# Generated by Django 4.2.7 on 2023-11-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photogalrow',
            name='photo_size',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
